import esbuild from "esbuild";
import { readFileSync, watch } from "node:fs";
import { syncLocal } from "./scripts/sync-local.mjs";
import process from "process";
import { builtinModules } from "node:module";

const thirdPartyNotices = readFileSync(new URL("./THIRD_PARTY_NOTICES.md", import.meta.url), "utf8");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

${thirdPartyNotices}
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
    plugins: [{
        name: "sync-local-install",
        setup(build) {
            build.onEnd(async result => {
                if (result.errors.length === 0) await syncLocal();
            });
        },
    }],
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
        "node:*",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
});

if (prod) {
    await context.rebuild();
    await context.dispose();
} else {
    await context.watch();
    // CSS and manifest are not JS imports; rebuild on their filesystem events too.
    let timer;
    for (const file of ["styles.css", "manifest.json"]) {
        watch(file, () => {
            clearTimeout(timer);
            timer = setTimeout(() => { void context.rebuild().catch(console.error); }, 100);
        });
    }
}
